language: csharp
solution: Bletchley.Enigma.Simulator.sln
install:
 - nuget restore Bletchley.Enigma.Simulator.sln
script:
 - xbuild /p:Configuration=Release Bletchley.Enigma.Simulator.sln
 - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Bletchley.Enigma.Simulator.UnitTests/bin/Release/Bletchley.Enigma.Simulator.UnitTests.dll
