language: csharp
solution: Bletchley.sln
install:
 - nuget restore Bletchley.sln
script:
 - xbuild /p:Configuration=Release Bletchley.sln
 - mono ./packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./Bletchley.Enigma.Simulator.UnitTests/bin/Release/Bletchley.Enigma.Simulator.UnitTests.dll
